### ISSUE TITLE
Ebook generate error occur in current HonKit

### ISSUE THREAD

**Issue by tsuyoshicho** [vowstar/gitbook-plugin-uml#17]
see https://github.com/honkit/honkit/issues/142#issuecomment-715934872

> Probably, gitbook-plugin-uml generate *.svg on finish:before.
> However, HonKit copy resources on generateAssets.

There seems to be a plan to fix it as follows.
> Generate *.svg on page:before and it will fix this issue?

Either way, it seems that the timing must be before `generateAssets`.

**Comment by vowstar** [comment]
OK, thanks your report, I'll fix and test it later

**Comment by vowstar** [comment]
I try give it a fix and have updated the npm repo, please try again

**Comment by tsuyoshicho** [comment]
Thanks!! I try it.

**Comment by tsuyoshicho** [comment]
Ommmm...
https://github.com/tsuyoshicho/honkit-gen-sample/releases/tag/v5.0.2

ebook file generate success, but now do not contain UML SVG image.

(https://tsuyoshicho.github.io/honkit-gen-sample/doc/functionsample-md.html web as svg load lazy and dynamic, svg generate only success.)

**Comment by vowstar** [comment]
OK, I will try again and find how to make sure it generated before it use svg file

**Comment by vowstar** [comment]
I've tested your demo and have updated the npm repo, it seems works, please try again

**Comment by tsuyoshicho** [comment]
Great work!.

result as fine.
https://github.com/tsuyoshicho/honkit-gen-sample/releases/tag/v5.0.3

Thank you for your support.
This issue close.
