### ISSUE TITLE
The installation of node-plantuml fails

### ISSUE THREAD

**Issue by koichimatsuno** [vowstar/gitbook-plugin-uml#19]
The following error occurs.
```
Error: node-plantuml@0.9.1 postinstall: `npm run getpuml && node scripts/get-vizjs.js`
Exit status 1
```
I set the version of node-plantuml to 0.9.0 in the package.json dependencies as fine.

**Comment by vowstar** [comment]
> 0.9.1

It probably not a bug.
Check your network, as your describtion, the version 0.9.1 download the latest version of plantuml.jar and failed. You should clean the node modules and retry.
Lack many information in this issue, need your node.js version, npm version, and OS version.

**Comment by koichimatsuno** [comment]
Thanks for your reply.

node.js  v10.16.3  
npm 6.9.0  
os Microsoft Windows [Version 10.0.18362.1139]

**Comment by vowstar** [comment]
Could you try cd into ``node_modules/node-plantuml`` and  run ``npm run getpuml`` to test the download process?
If download success, this issue probably could fix.
The latest plantuml.jar file will download to ``node_modules/node-plantuml/vendor/plantuml.jar``
Nomally this process is automatically down, or something network error occured.

**Comment by vowstar** [comment]
I've try to reproduce your issue locally but it always successfully install and can't reproduce.

```bash
npm install --only=dev
...
> node-plantuml@0.9.1 postinstall /home/vowstar/Projects/2020/honkit/honkit-gen-sample/node_modules/node-plantuml
> npm run getpuml && node scripts/get-vizjs.js


> node-plantuml@0.9.1 getpuml /home/vowstar/Projects/2020/honkit/honkit-gen-sample/node_modules/node-plantuml
> node scripts/get-plantuml-jar.js

Downloading plantuml.jar version 1.2020.19
graphviz was found on the system. Skipping download of vizjs.
...
...
npx honkit build
info: 6 plugins are installed 
info: 6 explicitly listed 
info: plugin "uml is loaded
info: plugin "highlight is loaded
info: plugin "search is loaded
info: plugin "lunr is loaded
info: plugin "fontsettings is loaded
info: plugin "theme-default is loaded
info: found 5 pages 
info: found 16 asset files 
warn: "book" property is deprecated, use "this" directly instead 
warn: "this.generator" property is deprecated, use "this.output.name" instead 
warn: "navigation" property is deprecated 
warn: "options" property is deprecated, use config.get(key) instead 
info: >> generation finished with success in 0.9s !
```

I guess your problem is the network error when download ``plantuml.jar``

**Comment by koichimatsuno** [comment]
> Could you try cd into node_modules/node-plantuml and run npm run getpuml to test the download process?

```PS D:\test\test\node_modules\node-plantuml> npm run getpuml

> node-plantuml@0.9.1 getpuml D:\test\test\node_modules\node-plantuml
> node scripts/get-plantuml-jar.js

Downloading plantuml.jar version 1.2020.19
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 216.105.38.13:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

> I guess your problem is the network error when download plantuml.jar

That seems to be the case.
I'll check my network .
Thanks for your help.

**Comment by koichimatsuno** [comment]
It seems that proxy information must be set on each call to http.request. Node does not include a mechanism for global proxy settings.   
https://stackoverflow.com/questions/18586902/node-js-global-proxy-setting

The following link is the Electron's proxy file, and uses global-agent for node 10.0 and above  
https://github.com/electron/get/blob/master/src/proxy.ts  

I added the following line to get-plantuml-jar.js and it works.

```js
require('global-agent').bootstrap();
global.GLOBAL_AGENT.HTTPS_PROXY = 'proxy url';
```
This was the same for the original "node-plantuml", so I would like to close this issue.

**Comment by vowstar** [comment]
maybe node-plantuml need a update
