### ISSUE TITLE
Plugin is not working with [!include] directive

### ISSUE THREAD

**Issue by hiroshi-maeda** [vowstar/gitbook-plugin-uml#20]
In our documentation build system we are using Honkit with your plugin.
We tried to use [!include] directive
The files we tested are as follows.

test.md
```plantuml
@startuml
!include test.pu
@enduml
```

test.pu
```
@startuml
interface List
List : int size()
List : void clear()
List <|.. ArrayList
@enduml
```

The generated svg resulted in an error.
![934c2c1d74a0fa88cde5f9c34e56afddace63269](https://user-images.githubusercontent.com/35279122/127471986-58dce49b-a01a-463b-a8a4-9b99e76de800.png)

I wonder if you still support this plugin and could fix this issue. Or could give us a tip how to fix it.

**Comment by vowstar** [comment]
I'm trying to reproduce, but it works.

My nodejs version is :

```bash
node -v
v14.15.0
```

```bash
npx honkit build
info: 6 plugins are installed 
info: 6 explicitly listed 
info: plugin "uml" is loaded
info: plugin "highlight" is loaded
info: plugin "search" is loaded
info: plugin "lunr" is loaded
info: plugin "fontsettings" is loaded
info: plugin "theme-default" is loaded
info: found 1 pages 
info: found 2 asset files 
warn: "book" property is deprecated, use "this" directly instead 
warn: "this.generator" property is deprecated, use "this.output.name" instead 
warn: "navigation" property is deprecated 
warn: "options" property is deprecated, use config.get(key) instead 
info: >> generation finished with success in 0.7s !
```

And all files looks OK.

![Screenshot from 2021-07-30 00-22-04](https://user-images.githubusercontent.com/394260/127528935-9e9da387-7d2d-475c-a895-c6b1f6fd4e14.png)


README.md
````markdown

```puml
@startuml
!include test/test.plantuml
@enduml
```
````

SUMMARY.md
````markdown
# Summary

* [Introduction](README.md)
````

test/test.plantuml

```puml
@startuml
(A)->(B)
@enduml
```


My files in this attachments, including SUMMARY.md, README.md, book.json, _book and asserts.
[build_success.zip](https://github.com/vowstar/gitbook-plugin-uml/files/6902035/build_success.zip)

**Comment by vowstar** [comment]
https://github.com/vowstar/gitbook-plugin-uml/commit/c7bcc6b09fc67843f89042878c95eb782b5b3b80

In order to test this problem more rigorously, I added a test case just now to prove the correctness of the process.

The build result is passed, https://github.com/vowstar/gitbook-plugin-uml/runs/3193927482

```json
  "node_js": [
    "12",
    "16",
    "lts/*"
  ]
```

It passd with nodejs 12, 16 and current LTS under travis CI.

https://app.travis-ci.com/github/vowstar/gitbook-plugin-uml/builds/234008372

 ✔ should correctly use external plantuml file specified by ```puml @startuml !include ... @enduml tag (5810ms)

**Comment by hiroshi-maeda** [comment]
Thanks for the quick reply.
Sure enough, I redid it with the minimum configuration and it worked.
However, it still doesn't work with the project that caused the error.
I will close this issue and open it again when I find the problem.

**Comment by hiroshi-maeda** [comment]
I know what the problem is.
At the top level of the project, there is no problem.
The error occurs when there are Markdown files under a directory.

dir/dir_test.md
~~~
# dir_test
```plantuml
@startuml
!include dir_test.plantuml
@enduml
```
~~~

dir/dir_test.plantuml
~~~
@startuml
(C)->(D)
@enduml
~~~

The generated svg resulted in an error.
![cce711447344d47ddcb47d91a95f1761a0649c2b](https://user-images.githubusercontent.com/35279122/127594222-ebf0c29b-0b10-4bbd-87d2-f16b2df3d13a.png)

This problem occurs when the Markdown file is located under a directory.

Note that if you replace the path in the [!include dir_test.plantuml] part of the **dir_test.md** file with an absolute path, the image will be generated normally.

**Comment by vowstar** [comment]
could you try

> dir/dir_test.md
> dir/dir_test.plantuml
````puml
```plantuml
@startuml
!include dir/dir_test.plantuml
@enduml
```
````

Because the plantuml have a search path root is gitbook document root, so a prefix dir needed.

**Comment by hiroshi-maeda** [comment]
Thanks for the quick reply.
I was indeed able to respond with what you said.
However, in my local environment, I am using the following to make it work.
- VSCode
   - Markdown All in One
- GraphViz

There, this path specification causes an error in the opposite direction.
So this is a specification of Honkit (GitBook) and there is nothing I can do about it.
Is there any way to fix this?

**Comment by vowstar** [comment]
> Thanks for the quick reply.
> I was indeed able to respond with what you said.
> However, in my local environment, I am using the following to make it work.
> 
> * VSCode
>   
>   * Markdown All in One
> * GraphViz
> 
> There, this path specification causes an error in the opposite direction.
> So this is a specification of Honkit (GitBook) and there is nothing I can do about it.
> Is there any way to fix this?

Thanks for your information, I understand what happend. This is a bug, I'm writing code and try to fix it.

**Comment by vowstar** [comment]
I've add code to support uml in nested dir, and refactor the test case to check it. https://github.com/vowstar/gitbook-plugin-uml/commit/e1180584deda8e09154528593ff9d32bd3523ed4
Could you try v1.2.10? It may fixed this issue.

**Comment by hiroshi-maeda** [comment]
I apologize for the delay in getting back to you.

The problem I was having was solved (on Windows).
To be honest, it's not working on Linux, but I feel like that's a problem with my environment.
I want to make sure, so it will take some more time.

**Comment by vowstar** [comment]
https://github.com/vowstar/gitbook-plugin-uml/commit/e1180584deda8e09154528593ff9d32bd3523ed4#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R43-R47
```nodejs
            if (require("process").platform == 'win32') {
                config.include = includePath + ';' + cwdPath;
            } else {
                config.include = includePath + ':' + cwdPath;
            }
```
The only different between linux and windows is ":" or ";" in include path, i only tested on linux. Thank you for windows test result.

**Comment by hiroshi-maeda** [comment]
I figured out why it didn't work on Linux.

I am Japanese. Therefore, I use Japanese (multibyte characters) for directory names.
In that case, it does not work well. If you change it to single byte characters, it will work fine.
If the file name is in Japanese, it will work fine.

Example: 
　docs/01_設計/設計書.md → NG
  docs/01_design/document.md → OK
  docs/01_design/設計書.md → OK

Is there any possible solution to this problem?

**Comment by vowstar** [comment]
It may be an encoding bug. Under my environment it is OK, I always use unicode characters as directory name (including zh-Hans/zh-Hant/ja-JP).

[cjk_nested_test.zip](https://github.com/vowstar/gitbook-plugin-uml/files/6920717/cjk_nested_test.zip)

I've created a test case (above attachment) to test ``docs/01_設計/設計書.md ``, it seems OK under my environment(only linux).

![Screenshot from 2021-08-03 10-51-42](https://user-images.githubusercontent.com/394260/127950840-73535516-0137-4acb-af04-b5cdc6e72bd5.png)


I guess this bug is related to locale setting, may be plantuml.jar got the error encoding with including directory. The UTF-8 encoding (ja_JP.UTF-8/en_US.utf8/zh_CN.UTF-8) always OK.

My system:

```
uname -a
Linux t480 5.13.6-gentoo-x86_64 #1 SMP Thu Jul 29 10:56:50 CST 2021 x86_64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz GenuineIntel GNU/Linux

cat /etc/lsb-release 
DISTRIB_ID="Gentoo"


```


My locale settings:

```
zh_CN.GB18030 GB18030
zh_CN.GBK GBK
zh_CN.UTF-8 UTF-8
zh_CN GB2312
ja_JP EUC-JP
ja_JP.EUC-JP EUC-JP
ja_JP.UTF-8 UTF-8
en_US ISO-8859-1
en_US.UTF-8 UTF-8
```

```bash
locale

LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

I'm using docker environment to generate document, the Dockerfile and locale configuration could be (debian & ubuntu):

```Dockerfile
FROM debian:sid
LABEL maintainer="Huang Rui"

## Configure packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq \
        locales \
        locales-all \
        xfonts-utils \
        fontconfig \
        wget \
        git \
        python3 \
        python3-pip \
        p7zip-full \
        p7zip-rar \
        s-nail

## Install noto fonts
RUN DEBIAN_FRONTEND=noninteractive apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq \
        fonts-noto-cjk


## Configure locale
RUN locale-gen && \
    echo "ja_JP EUC-JP" > /etc/locale.gen && \
    echo "ja_JP.EUC-JP EUC-JP"  >> /etc/locale.gen && \
    echo "ja_JP.UTF-8 UTF-8"  >> /etc/locale.gen && \
    echo "zh_CN.UTF-8 UTF-8"  >> /etc/locale.gen && \
    echo "zh_CN GB2312" >> /etc/locale.gen && \
    echo "zh_CN.GB18030 GB18030" >> /etc/locale.gen && \
    echo "zh_CN.GBK GBK" >> /etc/locale.gen && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    echo 'LANG="en_US.UTF-8 UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

## Install calibre
RUN DEBIAN_FRONTEND=noninteractive apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq \
        calibre

## Configure TNVM
RUN export TNVM_SOURCE_GIT="https://github.com/aliyun-node/tnvm.git" && \
    export TNVM_DIR="$HOME/.tnvm" && \
    export METHOD=git && \
    git clone ${TNVM_SOURCE_GIT} $TNVM_DIR && \
    cd "$TNVM_DIR" && \
    git checkout --quiet master && \
    bash install.sh

## Configure node
ARG NODE_VERSION=node-v12.18.3
RUN . "$HOME/.tnvm/tnvm.sh" && \
    tnvm install ${NODE_VERSION} && \
    tnvm use ${NODE_VERSION}

## Configure npm
RUN . "$HOME/.tnvm/tnvm.sh" && \
    npm config set registry https://registry.npm.taobao.org && \
    npm i -g nrm && \
    nrm use taobao

## Setup openssl to fix phantomjs libssl_conf.so problem
ENV OPENSSL_CONF=/etc/ssl/

## Configure honkit
RUN . "$HOME/.tnvm/tnvm.sh" && \
    npm install -g --unsafe-perm honkit

## Configure gitbook plugins
RUN . "$HOME/.tnvm/tnvm.sh" && \
    npm install -g --ignore-scripts gitbook-plugin-footnote-string-to-number && \
    npm install -g --ignore-scripts gitbook-plugin-search-pro && \
    npm install -g --ignore-scripts gitbook-plugin-anchors && \
    npm install -g --ignore-scripts gitbook-plugin-flow && \
    npm install -g --ignore-scripts gitbook-plugin-sequence && \
    npm install -g --ignore-scripts gitbook-plugin-katex-ng && \
    npm install -g --ignore-scripts gitbook-plugin-echarts && \
    npm install -g --ignore-scripts gitbook-plugin-uml && \
    npm install -g --ignore-scripts gitbook-plugin-prism

```

Could you provide more information to debug this problem? 
Which linux distribution are you using?

```bash
# run locale to get locale settings
locale
# get distro info
cat /etc/lsb-release
# get nodejs info
node -v
```

**Comment by hiroshi-maeda** [comment]
I saw and understood your Docker configuration.
I'm currently running it on Docker, but since it was set to the minimum configuration, it lacked the Japanese locale.
I set it up the same way and it worked.

Thanks for all the information!
Thank you very much.
