### ISSUE TITLE
Two or more images in assets/ directory are not copied into _build/

### ISSUE THREAD

**Issue by yumeto-yamagishi** [vowstar/gitbook-plugin-uml#22]
Related to #7

When markdown files contains multiple UML diagram, some image links in built HTML are broken and these diagram image is not shown in HTML.
More details, the link for UML defined in the FIRST position in markdown file is OK, but the others are always broken.

After building I checked the `assets/` directory and I confirmed all images are generated, but only ONE image was copied into `_build/assets/` directory.

**Comment by yumeto-yamagishi** [comment]
I found the following behavior by adding debug log in my local machine.

At the second call back of this plugin, the following `non-existing the target directory` checks always result to `false`.
https://github.com/vowstar/gitbook-plugin-uml/blob/731023b55baf8fe26af89d60d7a852854c0f7aee/index.js#L79

Because when the first time called back the target directory (represented by `destFilePath` )  is created.

Perhaps definition of `destFilePath` should not joining with `ASSET_PATH` but with `filePath`?
```js
var destFilePath = path.join(rootPath, filePath);
```

**Comment by vowstar** [comment]
Thanks for your reporting, this is a bug and confirmed.

**Comment by vowstar** [comment]
1.2.11 with fix released, please try again.

**Comment by yumeto-yamagishi** [comment]
@vowstar I've confirmed the coping behaves correctly.
It seems good for me! 
Thanks to your quick update.
