### ISSUE TITLE
assets/ is not copied into _book/ directory

### ISSUE THREAD

**Issue by dai0304** [vowstar/gitbook-plugin-uml#7]
In v0.1.10, that's all ok.
In v0.1.11, it has broken image link.

### reproduction

1. `git clone https://gist.github.com/a7088b874a7055e0f8b5fc2dcbf0131e.git`
2. `cd a7088b874a7055e0f8b5fc2dcbf0131e`
3. `gitbook install && gitbook serve`
4. Open http://localhost:4000
5. It has broken image link

**Comment by vowstar** [comment]
Thanks, I'll check this problem

**Comment by vowstar** [comment]
This problem is fixed in gitbook-plugin-uml@0.1.12, now it support retina display and image link is OK.
