### ISSUE TITLE
Please update node-plantuml

### ISSUE THREAD

**Issue by kuttsun** [vowstar/gitbook-plugin-uml#9]
node-plantuml accesses sourceforge, but in my environment, access is restricted.
However, this seems to be solved in 0.7.0.

https://github.com/markushedvall/node-plantuml/issues/20

Please update node-plantuml to 0.7.0.

**Comment by vowstar** [comment]
It merged in https://github.com/vowstar/gitbook-plugin-uml/pull/10, thanks!
